plugins: 
    - jekyll-mermaid

title: Thèse professionnelle
email: quentin@widlocher.com
author: Quentin Widlocher
description: >-
    Thèse professionnelle de fin de cursus, sur les applications native, web et hybrides.
baseurl: 'ThesePro'
github_username: QuentinWidlocher

# Build settings
theme: minima
collections:
    chapters:
        output: true
        permalink: /:collection/:title

mermaid:
  src: '/ThesePro/assets/mermaid.min.js'