name: Deploy website

on:
  push:
    branches: [ master, Jekyll ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Jekyll site.
      uses: meitar/jekyll-builder-for-github-pages-action@v1
      with:
        jekyll_build_opts: -s ./jekyll/
        pre_build_commands: |
          rm ./jekyll/_chapters/*
          cp -R ./These/. ./jekyll/_chapters
          echo
          echo Chapters :
          echo $(ls ./jekyll/_chapters)
          echo
        post_build_commands : echo $(ls ./jekyll)
        secret_gh_pages_api_token: ${{ secrets.GH_PAGES_TOKEN }}
