name: Deploy website

on:
  push:
    branches: [ master, Jekyll ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Jekyll site.
      uses: meitar/jekyll-builder-for-github-pages-action@v1
      with:
        gh_pages_publishing_source: jekyll
        pre_build_commands: |
          mv -f ./These ./jekyll/_chapter
          echo Chapters :
          echo $(ls -l ./jekyll/_chapter)
        post_build_commands: mv ./jekyll/_site ./docs
        secret_gh_pages_api_token: ${{ secrets.GH_PAGES_TOKEN }}
